# Default multi-robot training scenario in the warehouse world
name: warehouse_navigation
# Gazebo world file path
world: /data/lzq/gazebo_rl_gym_ws/src/gazebo_rl_gym/worlds/warehouse.world
metadata:
  description: Two TurtleBot3 Waffle robots navigating the warehouse world.
  topic_timeout: 2.0

observation:
  normalize_scan: true

reward_debug: true            # 打印 reward 分解用于调试

robots:
  - name: forklift1
    preset: forklift
    pose:
      x: 2.0
      y: 0.0
      z: 0.0
      yaw: 3.14
    task:
      target_pos: [-2, -1, 0.0]   # 目标点世界坐标
  - name: forklift2
    preset: forklift
    pose:
      x: -3.0
      y: -1.0
      z: 0.0
      yaw: 0.0
    task:
      target_pos: [1, 0, 0.0]     # 目标点世界坐标


reward:
  type: displacement
  distance_scale: 1.0          # 鼓励移动（正值）
  smoothness_scale: -0.01      # 惩罚动作不平滑（负值）
  heading_penalty_scale: -0.1  # 朝向偏差惩罚（负值）
  collision_penalty: -10.0     # 碰撞惩罚（负值）
  min_range_penalty: -2.0      # 靠障碍太近惩罚（负值）
  min_range_threshold: 1    # lidar 小于该距离开始惩罚
  goal_reward: 20.0            # 到终点一次性奖励（正值）
  dist_reward_scale: 1.0       # 距离缩短奖励系数（正值）
  step_cost: -0.01              # 每步负奖励（负值）

  # 靠近终点时
  pose_gate_radius: 1.5        # 进入该距离后开始关注目标姿态
  yaw_reward_scale: -0.1        # 姿态奖励强度（调参用）

termination:                  # 终止条件
  min_height: -1.0
  collision: true         
  min_collision_range: 0.45  # 碰撞判定阈值（单位：米）

  # 严格位姿成功条件（终止用）
  success_pos: 0.05            # 位置误差容差（米）小于此视为到达目标点
  success_yaw: 0.087266        # 朝向误差容差（弧度）≈5°
  success_lin_vel_th: 0.02     # 线速度阈值（m/s）
  success_ang_vel_th: 0.05     # 角速度阈值（rad/s）
  success_stay_steps: 3        # 满足上述条件连续步数才算成功
